repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: debug-statements

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
        # Run the linter
    -   id: ruff
        name: "Ruff linting"
        # Run the formatter
    -   id: ruff-format
        name: "Ruff formatting"
