[tox]
requires =
    tox >= 4.22
min_version = 4.22
envlist =
    py{311,313}
skip_missing_interpreters = True

[gh-actions]
python =
    3.11: py311
    3.13: py313

[testenv]
dependency_groups = test
setenv =
    LC_ALL=C.UTF-8
    LANG=C.UTF-8
    PYTHONWARNINGS=once::DeprecationWarning
passenv = HOME
package = editable
commands =
    pytest -o junit_suite_name="{envname} unit tests" --cov={toxinidir}/src --cov-report=xml:reports/{envname}/coverage.xml --junitxml=reports/{envname}/unit-results.xml --verbose {posargs}
